# Generated by Django 3.1.5 on 2021-02-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0002_auto_20210203_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
