# Generated by Django 3.1.5 on 2021-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0005_auto_20210203_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='imagename',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
