# Generated by Django 3.1.5 on 2021-02-09 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0006_auto_20210205_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locatedate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 23, 23, 9, 646599)),
        ),
    ]
