# Generated by Django 3.1.5 on 2021-02-11 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0008_auto_20210209_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founder',
            old_name='imagename',
            new_name='Item_Found',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='imagename',
            new_name='Item_Lost',
        ),
        migrations.AlterField(
            model_name='founder',
            name='founddate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 42, 31, 376545)),
        ),
        migrations.AlterField(
            model_name='user',
            name='locatedate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 42, 31, 375549)),
        ),
    ]
