# Generated by Django 3.1.5 on 2021-02-11 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0009_auto_20210211_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founder',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='founder',
            old_name='desc',
            new_name='Description_of_Item',
        ),
        migrations.RenameField(
            model_name='founder',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='founder',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='founder',
            old_name='photo',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='founder',
            old_name='name',
            new_name='Your_Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='desc',
            new_name='Description_of_Item',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Your_Name',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='founddate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locatedate',
        ),
        migrations.AddField(
            model_name='founder',
            name='Date_Found',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 50, 37, 606583)),
        ),
        migrations.AddField(
            model_name='user',
            name='Date_Lost',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 50, 37, 606583)),
        ),
    ]
