# Generated by Django 3.1.5 on 2021-02-11 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0010_auto_20210211_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founder',
            old_name='Location',
            new_name='Location_You_Found',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Location',
            new_name='Location_You_Lost',
        ),
        migrations.AlterField(
            model_name='founder',
            name='Date_Found',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 54, 2, 196191)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date_Lost',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 54, 2, 196191)),
        ),
    ]
