# Generated by Django 3.1.5 on 2021-02-11 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0011_auto_20210211_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founder',
            old_name='Location_You_Found',
            new_name='Location_Found',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Location_You_Lost',
            new_name='Location_Lost',
        ),
        migrations.AlterField(
            model_name='founder',
            name='Date_Found',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 55, 12, 601880)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date_Lost',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 21, 55, 12, 601880)),
        ),
    ]
