# Generated by Django 3.1.5 on 2021-02-14 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0012_auto_20210211_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='Date_Found',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 13, 59, 27, 891835)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date_Lost',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 13, 59, 27, 890805)),
        ),
    ]
