# Generated by Django 3.1.5 on 2021-02-15 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0013_auto_20210214_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='Phone_No',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='Phone_No',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='founder',
            name='Date_Found',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 21, 10, 33, 879211)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date_Lost',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 21, 10, 33, 877920)),
        ),
    ]
