# Generated by Django 3.1.5 on 2021-02-15 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0014_auto_20210215_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='Date_Found',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 21, 25, 48, 211602)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date_Lost',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 21, 25, 48, 211602)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone_No',
            field=models.CharField(max_length=12),
        ),
    ]
