# Generated by Django 3.1.5 on 2021-02-15 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laf', '0015_auto_20210215_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='Date_Found',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 0, 34, 24, 965864)),
        ),
        migrations.AlterField(
            model_name='founder',
            name='Description_of_Item',
            field=models.CharField(default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='founder',
            name='Item_Found',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date_Lost',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 0, 34, 24, 965864)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Description_of_Item',
            field=models.CharField(default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='user',
            name='Item_Lost',
            field=models.CharField(default='', max_length=100),
        ),
    ]
